#!/usr/bin/env bash

config=$1
src="$(dirname $0)/src"

if [[ ! -f "$src/.env" ]]; then
  echo "cosMx2VIP: Please run ./install to setup necessary env variables"
  exit
fi

#condaEnv=$(head -n 1 $src/sys.yml)
#condaEnv=${condaEnv:1}
set -e
if [[ -f "$config" ]]; then
  env -i config="$config" src="$src" bash -c 'source $src/.env;eval $condaEnv;python -u $src/cosMx2VIP.py $config 2>&1 | tee -a $config.$(date +%Y%m%d).log'
elif [[ -d "$config" ]]; then
  env -i config="$config" src="$src" bash -c 'source $src/.env;eval $condaEnv;python -u $src/cosMx2VIP.py $config 2>&1'
else
  env -i src="$src" bash -c 'source $src/.env;eval $condaEnv;python -u $src/cosMx2VIP.py'
fi