#!/usr/bin/env bash

config=$1
src="$(dirname $0)/src"

if [[ ! -f "$src/.env" ]]; then
  echo "visium: Please run ./install to setup necessary env variables"
  exit
fi

set -e
if [[ -f "$config" ]]; then
  source $src/.env;eval $condaEnv;python -u $src/visium.py $config 2>&1 | tee -a $config.$(date +%Y%m%d).log
elif [[ -d "$config" ]]; then
  source $src/.env;eval $condaEnv;python -u $src/visium.py $config 2>&1
else
  source $src/.env;eval $condaEnv;python -u $src/visium.py
fi